In [26]:
import numpy as np

#softmax function example from udacity class


scores = [3.0,1.0,0.2]



def softmax_1d(x):
    """Compute softmax values for each sets of scores in x."""
    returnMe = np.array([],np.double)
    sum = np.sum([np.exp(val) for val in x])
    result = [np.exp(val)/sum for val in x]
    return np.array(result)

def softmax(x): 
    return np.exp(x)/ np.sum(np.exp(x),axis=0)
    



print(softmax(scores))
# Plot softmax curves
import matplotlib.pyplot as plt
x = np.arange(-2.0, 6.0, 0.1)
scores = np.vstack([x, np.ones_like(x), 0.2 * np.ones_like(x)])

print 'scores for plot'
print scores
print '----------------'


plt.plot(x, softmax(scores).T, linewidth=2)
plt.show()

print 'running test case 1d'
scores = [1.0, 2.0, 3.0]
print (softmax(scores))

print 'running test case 2d'
scores = np.array([[1, 2, 3, 6],
                   [2, 4, 5, 6],
                   [3, 8, 7, 6]])
print (softmax(scores))






[ 0.8360188   0.11314284  0.05083836]
scores for plot
[[ -2.00000000e+00  -1.90000000e+00  -1.80000000e+00  -1.70000000e+00
   -1.60000000e+00  -1.50000000e+00  -1.40000000e+00  -1.30000000e+00
   -1.20000000e+00  -1.10000000e+00  -1.00000000e+00  -9.00000000e-01
   -8.00000000e-01  -7.00000000e-01  -6.00000000e-01  -5.00000000e-01
   -4.00000000e-01  -3.00000000e-01  -2.00000000e-01  -1.00000000e-01
    1.77635684e-15   1.00000000e-01   2.00000000e-01   3.00000000e-01
    4.00000000e-01   5.00000000e-01   6.00000000e-01   7.00000000e-01
    8.00000000e-01   9.00000000e-01   1.00000000e+00   1.10000000e+00
    1.20000000e+00   1.30000000e+00   1.40000000e+00   1.50000000e+00
    1.60000000e+00   1.70000000e+00   1.80000000e+00   1.90000000e+00
    2.00000000e+00   2.10000000e+00   2.20000000e+00   2.30000000e+00
    2.40000000e+00   2.50000000e+00   2.60000000e+00   2.70000000e+00
    2.80000000e+00   2.90000000e+00   3.00000000e+00   3.10000000e+00
    3.20000000e+00   3.30000000e+00 

running test case 1d
[ 0.09003057  0.24472847  0.66524096]
running test case 2d
[[ 0.09003057  0.00242826  0.01587624  0.33333333]
 [ 0.24472847  0.01794253  0.11731043  0.33333333]
 [ 0.66524096  0.97962921  0.86681333  0.33333333]]


In [19]:

scores = np.array([[1, 2, 3, 6],
                   [2, 4, 5, 6],
                   [3, 8, 7, 6]])

list_result = []
for val in scores.T:
    #print 'val:', val, 'softmax(val):',softmax_1d(val)
    list_result.append(softmax_1d(val).tolist())
    
r = np.array(list_result)
print 'r.T:', r.T

val: [1 2 3] softmax(val): [ 0.09003057  0.24472847  0.66524096]
val: [2 4 8] softmax(val): [ 0.00242826  0.01794253  0.97962921]
val: [3 5 7] softmax(val): [ 0.01587624  0.11731043  0.86681333]
val: [6 6 6] softmax(val): [ 0.33333333  0.33333333  0.33333333]
r.T: [[ 0.09003057  0.00242826  0.01587624  0.33333333]
 [ 0.24472847  0.01794253  0.11731043  0.33333333]
 [ 0.66524096  0.97962921  0.86681333  0.33333333]]


In [ ]:
[[ 0.09003057  0.00242826  0.01587624  0.33333333]
 [ 0.24472847  0.01794253  0.11731043  0.33333333]
 [ 0.66524096  0.97962921  0.86681333  0.33333333]]